In [4]:
##EXERCÍCIOS

import numpy as np

### 1 Crie um vetor nulo de tamanho 10

In [20]:
vetor1=np.zeros((10),dtype=np.int16)
print(vetor1)

vetor2=np.zeros((5, 5),dtype=np.int16)
print(vetor1)

vetor3=np.zeros((3,3,3),dtype=np.int16)
print(vetor1)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


### 2 Como encontrar o tamanho da memória de qualquer matriz

In [21]:
print(vetor1.nbytes)
print(vetor2.nbytes)
print(vetor3.nbytes)

20
50
54


### 3 Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

In [24]:
vetor4=np.zeros((10),dtype=np.int16)
vetor4[4] = 1
print(vetor4)

[0 0 0 0 1 0 0 0 0 0]


### 4 Crie um vetor com valores que variam de 10 a 49

In [29]:
vetor5 = np.arange(10,50)
print(vetor5)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 5 Inverter um vetor (o primeiro elemento se torna o último)

In [31]:
vetor6 = vetor5[::-1]
print(vetor6)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 6 Crie uma matriz 3x3 com valores que variam de 0 a 8

In [33]:
lista7 = np.random.randint(8, size=(3,3))
print(lista7)

[[1 4 7]
 [7 3 3]
 [1 6 0]]


### 7 Crie uma matriz de identidade 3x3

In [36]:
lista8 = np.identity(3)
print(lista8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 8 Crie uma matriz 3x3x3 com valores aleatórios

In [41]:
lista9 = np.random.random(size=(3,3,3))
print(lista9)

[[[0.70273455 0.64584874 0.66267264]
  [0.96796168 0.30342141 0.96038201]
  [0.27704387 0.16441852 0.17979537]]

 [[0.56298631 0.67268006 0.6823895 ]
  [0.8721268  0.0765502  0.41816006]
  [0.7581039  0.97054306 0.3943028 ]]

 [[0.14597828 0.31764123 0.36050647]
  [0.43508578 0.85308828 0.60732567]
  [0.58487779 0.12895049 0.01774388]]]


### 9 Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

In [48]:
lista10 = np.random.random(size=(10,10))
print(lista10)

lista101 = np.amax(lista10)
print("\n Máximo da lista:", lista101)

[[0.10971942 0.39113075 0.38702799 0.21631244 0.82451723 0.74169788
  0.35082711 0.87740688 0.71926257 0.30453132]
 [0.68012993 0.88802211 0.17413279 0.04953701 0.94912272 0.34405998
  0.02157607 0.66435582 0.54487406 0.29851948]
 [0.75066708 0.66951904 0.69899341 0.72897456 0.84048723 0.51354328
  0.33451284 0.36674643 0.39733588 0.09865355]
 [0.66798173 0.97697909 0.98561926 0.48767355 0.47743731 0.7817158
  0.76236815 0.63611935 0.43520416 0.82283964]
 [0.98869033 0.82687606 0.27124252 0.82925405 0.29343412 0.97407367
  0.13074663 0.50976352 0.68605332 0.79319607]
 [0.29802264 0.73641927 0.09693041 0.30207116 0.75181291 0.97236839
  0.11517907 0.91982219 0.40293446 0.63112977]
 [0.84466677 0.57313948 0.53717582 0.8519825  0.92412432 0.64624183
  0.43746809 0.06205905 0.48950616 0.71346269]
 [0.07887134 0.24233612 0.37360368 0.051744   0.70924708 0.88000586
  0.67136415 0.7895819  0.30650371 0.65886841]
 [0.0887174  0.64749124 0.11920502 0.00193332 0.65681172 0.87150609
  0.6197832  

### 10 Crie um vetor aleatório de tamanho 30 e encontre o valor médio

In [57]:
vetor11 = np.random.randint(100, size=30)
print(vetor11)
vetor111 = np.average(vetor11)
print("A média é: %.2f" % vetor111)

[18 79 11 82 40 32 28 70 32 98 24 90 44 30 34 91 50 43 19 24  7  1 54  2
 84  9 99 12 72 53]
A média é: 44.40


### 11 Crie uma matriz 2D com 1 na borda e 0 dentro

In [63]:
vetor12=np.ones((3,3),dtype=np.int16)
vetor12[1,1] = 0
print(vetor12)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [76]:
matriz2d = np.zeros((5,5))
print(matriz2d)

matriz2d[0] = 1
matriz2d[:,0] = 1
matriz2d[-1,:] = 1
matriz2d[:,-1] = 1
print(matriz2d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 12 Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal

In [227]:
n = 6

lista131 = np.arange(1,n+1)
lista132 = np.zeros((n, n), int)
lista132 = np.diag(lista131)

lista133 = np.zeros((1, n), int)

lista134 = np.append(lista133, lista132, axis=0)

lista135 = np.delete(lista134, n, axis=0)
print(lista135)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [235]:
n = 7

lista132 = np.zeros((n, n), int)
lista132 = np.diag(np.arange(1,n+1))

print(np.delete(np.append(np.zeros((1, n), int), lista132, axis=0), n, axis=0))


[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]]


### 13 Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

In [30]:
matriz13 = np.zeros(10,
[('position', [ ('x', float, 1),('y', float, 1)]),
 ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])

print(matriz13)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/home/cv/miniconda3/envs/ambiente1/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  This is separate from the ipykernel package so we can avoid doing imports until


### 14 Subtrair a média de cada linha de uma matriz

In [255]:
lista141 = np.random.random(size=(10,10))

for i, array in enumerate(lista141):
    media = np.average(array)
    print("A média do vetor %d é igual a %.2f" % (i,media))

A média do vetor 0 é igual a 0.57
A média do vetor 1 é igual a 0.45
A média do vetor 2 é igual a 0.35
A média do vetor 3 é igual a 0.36
A média do vetor 4 é igual a 0.41
A média do vetor 5 é igual a 0.62
A média do vetor 6 é igual a 0.54
A média do vetor 7 é igual a 0.45
A média do vetor 8 é igual a 0.58
A média do vetor 9 é igual a 0.43


### 15 Como encontrar o valor mais frequente em uma matriz?

In [269]:
import numpy as np
from scipy import stats

lista150 = np.array([[[ 0,  1,  2,  3,  4],
                  [ 5,  6,  7,  8,  9],
                  [10, 11, 12, 13, 14],
                  [15, 16, 17, 18, 19]],

                 [[ 0,  1,  2,  3,  4],
                  [ 5,  6,  0,  8,  9],
                  [10, 11, 12, 13, 14],
                  [15, 16, 17, 18, 19]],

                 [[40, 40, 42, 43, 44],
                  [45, 46, 0, 48, 49],
                  [50, 51, 52, 53, 54],
                  [55, 56, 57, 58, 59]]])

lista151 = stats.mode(lista150, axis=None)
print(lista151)

ModeResult(mode=array([0]), count=array([4]))


### 16 Crie uma matriz a partir de um arquivo

In [11]:
matriz16 = np.loadtxt("./matriz17.txt", dtype=np.int16)
print(matriz16)

[[4 3 2 2 3 0 4 4 0 2]
 [1 1 2 1 1 3 0 0 1 3]
 [0 2 3 3 1 0 3 3 0 2]
 [4 0 4 1 2 1 4 2 2 2]
 [3 1 1 0 4 4 2 3 2 1]
 [1 4 3 4 3 3 1 1 4 1]
 [2 1 0 0 1 3 3 3 1 3]
 [1 2 1 1 4 0 0 4 1 1]
 [4 0 2 2 4 0 0 1 0 0]
 [4 0 4 4 3 0 1 4 2 1]]


# 17 Crie uma matriz com valores aleatórios e salve para um arquivo

In [12]:
matriz17 = np.random.randint(5, size=(10, 10))
print(matriz17)

np.savetxt("./matriz17.txt", matriz17)

[[2 4 2 0 3 4 4 4 3 3]
 [2 3 1 1 2 1 0 0 4 3]
 [3 0 3 0 4 0 2 0 2 2]
 [0 3 3 3 2 4 3 0 2 2]
 [1 0 2 4 3 1 4 3 2 2]
 [1 4 1 0 4 2 3 3 4 4]
 [3 2 2 4 3 4 2 2 2 2]
 [3 2 1 2 3 3 4 4 3 2]
 [0 4 3 3 0 2 4 2 3 0]
 [0 0 3 1 3 0 3 1 1 2]]
