### EXERCICIOS DA AULA

- Crie um array com 10 elementos usando a função arange
- Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape
- Crie duas matrizes bidimensionais com valores aleatórios
- Calcule a transposta de cada matriz
- Multiplique as duas matrizes
- Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?
- Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha

In [2]:
import numpy as np

lista1 = np.arange(9)
print("Ex 1: ", lista1)

nova_lista1 = np.reshape(lista1, (3,3))
print("\nEx 2:\n", nova_lista1)

lista1_random = np.random.random((2,3))
print("\nEx 3: \n", lista1_random)

lista2_random = np.random.randint(5, size=(2, 3))
print(lista2_random)

print("\nEx 4: Transposta 1\n", np.transpose(lista1_random))
print("\nEx 4: Transposta 2\n", np.transpose(lista2_random))

mult_lista = np.multiply(lista1_random, lista2_random)
print("\nEx 5: Multiplicacao\n", mult_lista)

np.savetxt("/home/cv/lista1_random.txt", lista1_random)
np.savetxt("/home/cv/lista2_random.txt", lista2_random)

print("\nQuantidade de bytes da lista:\n", mult_lista.nbytes)

#PARA A SOLUÇÃO DO EXERCICIO 6, OPTEI POR SOMAR POR LINHA CADA MATRIZ E DEPOIS FAZER UMA COMBINADA DAS DUAS

print("\nEx 6:")
lista5 = np.random.randint(10, size=(3,3))
lista6 = np.random.randint(10, size=(3,3))
print("lista 5: \n", lista5)
print("lista 6: \n", lista6)

lista51 = np.sum(lista5,axis=1)
lista61 = np.sum(lista6,axis=1)
print("lista 5 com somatório das linhas:", lista51)
print("lista 6 com somatório das linhas:", lista61)

lista7 = np.add(lista51, lista61)
print("\nlista 7 somando a lista51 e lista61:", lista7)

Ex 1:  [0 1 2 3 4 5 6 7 8]

Ex 2:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Ex 3: 
 [[0.32659215 0.8486322  0.23076547]
 [0.95516579 0.20622506 0.24674834]]
[[0 1 1]
 [0 4 4]]

Ex 4: Transposta 1
 [[0.32659215 0.95516579]
 [0.8486322  0.20622506]
 [0.23076547 0.24674834]]

Ex 4: Transposta 2
 [[0 0]
 [1 4]
 [1 4]]

Ex 5: Multiplicacao
 [[0.         0.8486322  0.23076547]
 [0.         0.82490022 0.98699337]]

Quantidade de bytes da lista:
 48

Ex 6:
lista 5: 
 [[8 9 7]
 [4 3 1]
 [9 4 8]]
lista 6: 
 [[7 4 9]
 [6 1 1]
 [0 9 2]]
lista 5 com somatório das linhas: [24  8 21]
lista 6 com somatório das linhas: [20  8 11]

lista 7 somando a lista51 e lista61: [44 16 32]
