# Atividades

### Crie um array com 10 elementos usando a função arange.

In [5]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape.

In [12]:
a = np.arange(10)
print("ndarray: ")
print(a)

a = a.reshape(2,5)
print("reshaped ndarray: ")
print(a)

ndarray: 
[0 1 2 3 4 5 6 7 8 9]
reshaped ndarray: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


### Crie duas matrizes bidimensionais com valores aleatórios.

In [19]:
a = np.random.random((2, 1))
print("random matrix:")
print(a)

random matrix:
[[0.61391865]
 [0.79353655]]


In [22]:
a = np.random.random((2, 3))
print("random matrix:")
print(a)

random matrix:
[[0.69466313 0.03692139 0.50769743]
 [0.58867483 0.25060766 0.08793431]]


### Calcule a transposta de cada matriz.

In [25]:
a = np.random.random((2,3))*10
print("Original matrix:")
print(a)

Original matrix:
[[2.36440279 2.64361246 7.08685859]
 [6.59399905 9.9743376  3.40088008]]


In [26]:
b = a.transpose()
print("Transposed matrix:")
print(a)

Transposed matrix:
[[2.36440279 6.59399905]
 [2.64361246 9.9743376 ]
 [7.08685859 3.40088008]]


### Multiplique as duas matrizes.

In [29]:
a = np.random.random((2,3))*10
b = a.transpose()
print("Matrix 1:")
print(a)
print("Matrix 2:")
print(b)
c = np.dot(a, b)
print("Multiplicação dos arquivos:")
print(c)

Matrix 1:
[[5.4333946  3.69094621 8.41953334]
 [1.84995799 8.17121117 0.06062745]]
Matrix 2:
[[5.4333946  1.84995799]
 [3.69094621 8.17121117]
 [8.41953334 0.06062745]]
Multiplicação dos arquivos:
[[114.03340258  40.72150747]
 [ 40.72150747  70.19471229]]


### Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?

In [40]:
a = np.random.random((2,3))*10
b = a.transpose()
np.savetxt("entrada1", a)
np.savetxt("entrada2", b)
c = np.dot(a, b)
np.savetxt("saida", c)


In [45]:
np.loadtxt("saida")

array([[ 99.77238004,  76.34352681],
       [ 76.34352681, 108.57051602]])

### Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha.

In [58]:
a = np.random.random((2,1))
print("Matrix 1:")
print(a)
b = np.random.random((2,2))
print("Matrix 2:")
print(b)
np.concatenate((a,b), axis=1)

Matrix 1:
[[0.13185446]
 [0.25427326]]
Matrix 2:
[[0.41705465 0.95406143]
 [0.48831718 0.3356299 ]]


array([[0.13185446, 0.41705465, 0.95406143],
       [0.25427326, 0.48831718, 0.3356299 ]])