In [1]:
# Lista de Atividades numoy - Rafael Loni Martins



import numpy as np


# Crie um vetor nulo de tamanho 10
v1 = np.zeros(10)
print(v1)

v11 = np.empty(10)
print(v11)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
# Como encontrar o tamanho da memória de qualquer matriz
v1.dtype

dtype('float64')

In [3]:
# Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
v2 = np.zeros(10)
v2[4] = 1
print(v2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
# Crie um vetor com valores que variam de 10 a 49
v3 = np.arange(10,49)
print(v3)

v4 = np.arange(10,49,0.85)
print(v4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[10.   10.85 11.7  12.55 13.4  14.25 15.1  15.95 16.8  17.65 18.5  19.35
 20.2  21.05 21.9  22.75 23.6  24.45 25.3  26.15 27.   27.85 28.7  29.55
 30.4  31.25 32.1  32.95 33.8  34.65 35.5  36.35 37.2  38.05 38.9  39.75
 40.6  41.45 42.3  43.15 44.   44.85 45.7  46.55 47.4  48.25]


In [64]:
# Inverter um vetor (o primeiro elemento se torna o último)
v5 = np.flip(v3)
print(v5)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [66]:
# Crie uma matriz 3x3 com valores que variam de 0 a 8
# (limite inferior, limite superior, tamanho)
M3x3 = np.random.randint(0,8,(3,3))
print(M3x3)

[[5 4 0]
 [4 2 5]
 [3 1 1]]


In [67]:
# Crie uma matriz de identidade 3x3
I3 = np.identity(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
# Crie uma matriz 3x3x3 com valores aleatórios
M3x3r = np.random.random((3,3))
print(M3x3r)

M3x3r2 = np.random.randint(0,100,(3,3))
print(M3x3r2)


[[0.46174786 0.8402241  0.24688889]
 [0.03436031 0.01919375 0.74517401]
 [0.07861994 0.17171855 0.99749897]]
[[63 82 87]
 [ 8 78  7]
 [53 43 87]]


In [78]:
# Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
M10x10 = np.random.randint(0,100,(10,10))
print(M10x10)
print(np.min(M10x10))
print(np.max(M10x10))


[[19 10 79  9 29 25 41 95 60 43]
 [82 51 99  9 70 62 38 99 24 86]
 [88  0 19 60 82 96 71 62 49 75]
 [44 15 95 70 81 50 52 68 62 88]
 [53  1  3 19  4 15 61 15 90 23]
 [70 18 86 31 96  8 32  8  6  5]
 [26 13 55 25  5 91 30 84 36 18]
 [70 63 14 42 18 88 78 37 64 82]
 [80 93 47 88 20 33 62 81  9 81]
 [ 7 57 93 61 93  6 73 84 75 82]]
0
99


In [80]:
# Crie um vetor aleatório de tamanho 30 e encontre o valor médio
V30 = np.random.random(30)
print(V30)
print(np.mean(V30))

[0.99053415 0.39450003 0.87057638 0.60195719 0.48387076 0.80299243
 0.53182424 0.09399995 0.14925391 0.99644464 0.51038089 0.5987941
 0.14896078 0.10613214 0.96394962 0.13607078 0.94479466 0.24596297
 0.64135571 0.19066826 0.64785066 0.05347837 0.64660283 0.74918341
 0.11175107 0.9614964  0.28594243 0.05524597 0.516761   0.49713144]
0.4976155732869783


In [120]:
# Crie uma matriz 2D com 1 na borda e 0 dentro
M101 = np.zeros((10,10))
M101[0] = 1
M101[9] = 1
np.transpose(M101)[0] = 1
np.transpose(M101)[9] = 1
print(M101)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [117]:
# Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
M5x5 = np.identity(5)
M5x5[1][0] = 1
M5x5[2][1] = 2
M5x5[3][2] = 3
M5x5[4][3] = 4
print(M5x5)


[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


In [5]:
# Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

Mrgb2= np.full((800,1200,3),1)
#Mrgb2[::-50] = 150
#np.transpose(Mrgb2)[::-50] = 150
#Mrgb2[100:500:-10] = 220
#Mrgb2[50:-50] = 255
count = 0.01
for i in range(0,800,1):
    for j in range(0,1200,100):
        for k in range(3):
            Mrgb2[i][j][k] = 255
for i in range(0,800,100):
    for j in range(0,1200,1):
        for k in range(3):
            Mrgb2[i][j][k] = 255



from PIL import Image
img = Image.fromarray(Mrgb2.astype("uint8"), "RGB")
img.show()



array = np.zeros([100, 200, 4], dtype=np.uint8)
array[:,:100] = [255, 128, 0, 255] #Orange left side
array[:,100:] = [0, 0, 255, 255]   #Blue right side

# Set transparency depending on x position
for x in range(200):
    for y in range(100):
        array[y, x, 3] = x
img2 = Image.fromarray(array)
#img2.show()



print(Mrgb2)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[255 255 255]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 ...

 [[255 255 255]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[255 255 255]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]

 [[255 255 255]
  [  1   1   1]
  [  1   1   1]
  ...
  [  1   1   1]
  [  1   1   1]
  [  1   1   1]]]


In [148]:
# Subtrair a média de cada linha de uma matriz

Mmean = np.random.randint(0,100,(5,5))
print(Mmean)
print(np.mean(Mmean))
print(Mmean - np.mean(Mmean))


[[17 63 90 35 93]
 [ 6 85 74  6 19]
 [16 36 29 30 83]
 [70 20 55 79 92]
 [10 48 37 93 53]]
49.56
[[-32.56  13.44  40.44 -14.56  43.44]
 [-43.56  35.44  24.44 -43.56 -30.56]
 [-33.56 -13.56 -20.56 -19.56  33.44]
 [ 20.44 -29.56   5.44  29.44  42.44]
 [-39.56  -1.56 -12.56  43.44   3.44]]


In [167]:
#Como encontrar o valor mais frequente em uma matriz?


Mmoda = np.random.randint(0,5,10)
print(Mmoda)
counts = np.bincount(Mmoda)
print(counts)
print (np.argmax(counts))



[2 3 4 0 4 2 2 4 4 2]
[1 0 4 1 4]
2


In [11]:
# Crie uma matriz a partir de um arquivo

m = np.genfromtxt("matriz4numpy.csv",delimiter= "",skip_header = 0)
print(m)



[[1. 0. 2. 3. 4. 5.]
 [4. 5. 6. 4. 6. 4.]
 [0. 1. 2. 3. 4. 5.]]


In [165]:
# crie uma matriz com valores aletaórios e salve para um arquivo

Mrand = np.random.random((5,5))
print(Mrand)

np.savetxt("matrizaleatorio5x5", Mrand)



[[0.3299225  0.4189563  0.44465936 0.84307875 0.70662768]
 [0.08972459 0.64451701 0.3692802  0.53033778 0.32545261]
 [0.60791454 0.17679351 0.16809512 0.33882473 0.71570218]
 [0.46434941 0.2785511  0.43741404 0.47291065 0.84982346]
 [0.77416769 0.27132589 0.76084419 0.03087972 0.12221698]]


In [17]:
# Crie um array com 10 elementos usando a função arange

import numpy as np
array01 = np.arange(1,100,10)
print(array01)


[ 1 11 21 31 41 51 61 71 81 91]


In [18]:
# Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape
array02 = array01.reshape(2,5)
print(array02)


[[ 1 11 21 31 41]
 [51 61 71 81 91]]


In [20]:
# Crie duas matrizes bidimensionais com valores aleatórios
m1 = np.random.random((5,5))
m2 = np.random.random((5,5))
print(m1)
print(m2)

[[0.18439726 0.60145788 0.76103057 0.26117975 0.16596743]
 [0.1934855  0.88194251 0.42899209 0.61406538 0.12125765]
 [0.26286914 0.35206822 0.51432184 0.79254517 0.07033352]
 [0.30662552 0.72532641 0.11148412 0.6868573  0.0077481 ]
 [0.08638749 0.65687718 0.29646951 0.32551462 0.87489226]]
[[0.89766925 0.45718085 0.38935088 0.41012472 0.58701804]
 [0.47281806 0.7228685  0.45328358 0.61210375 0.14920839]
 [0.59185471 0.21282792 0.66492009 0.47976005 0.0277207 ]
 [0.31078787 0.47453645 0.92625968 0.17332406 0.87991011]
 [0.36738776 0.29579136 0.20973681 0.10508031 0.22442479]]


In [21]:
# calcule a transposta de cada matriz

print(np.transpose(m1))
print(np.transpose(m2))


[[0.18439726 0.1934855  0.26286914 0.30662552 0.08638749]
 [0.60145788 0.88194251 0.35206822 0.72532641 0.65687718]
 [0.76103057 0.42899209 0.51432184 0.11148412 0.29646951]
 [0.26117975 0.61406538 0.79254517 0.6868573  0.32551462]
 [0.16596743 0.12125765 0.07033352 0.0077481  0.87489226]]
[[0.89766925 0.47281806 0.59185471 0.31078787 0.36738776]
 [0.45718085 0.7228685  0.21282792 0.47453645 0.29579136]
 [0.38935088 0.45328358 0.66492009 0.92625968 0.20973681]
 [0.41012472 0.61210375 0.47976005 0.17332406 0.10508031]
 [0.58701804 0.14920839 0.0277207  0.87991011 0.22442479]]


In [26]:
# multiplique as duas matrizes

Mprod = np.dot(m1,m2)
print(Mprod)

[[1.04247333 0.85407745 1.12718048 0.87160121 0.48614529]
 [1.07997798 1.1445512  1.35456546 0.94418088 0.82460023]
 [0.97899066 0.88103544 1.35277216 0.7148203  0.93425092]
 [0.90049161 1.01645652 1.16012478 0.74307843 0.89742146]
 [0.98618837 0.99068164 1.01352339 0.72809433 0.63971206]]


In [39]:
# Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?
np.save("m1T", np.transpose(m1))
np.save("m2T", np.transpose(m2))
np.save("prodm1m2", Mprod)

np.savetxt("prodm1m2", Mprod)


AA = np.loadtxt("prodm1m2")
print(AA)

[[1.04247333 0.85407745 1.12718048 0.87160121 0.48614529]
 [1.07997798 1.1445512  1.35456546 0.94418088 0.82460023]
 [0.97899066 0.88103544 1.35277216 0.7148203  0.93425092]
 [0.90049161 1.01645652 1.16012478 0.74307843 0.89742146]
 [0.98618837 0.99068164 1.01352339 0.72809433 0.63971206]]


In [44]:
# Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha

m3 = np.random.random((7,3))
m4 = np.random.random((7,3))
print(m3)
print(m4)
m3m4 = np.concatenate((m3,m4),1)
print(m3m4)

[[0.26604553 0.14509708 0.95193781]
 [0.93106344 0.11450207 0.63144916]
 [0.29086591 0.52955083 0.55725123]
 [0.0628444  0.20233814 0.11742526]
 [0.09973558 0.52223712 0.77049028]
 [0.10844291 0.72172176 0.28230432]
 [0.62629961 0.04373182 0.92417003]]
[[0.44402484 0.73113497 0.88735496]
 [0.92331892 0.04783282 0.23329386]
 [0.79894906 0.06352008 0.20747816]
 [0.17378501 0.76516795 0.34302997]
 [0.55369917 0.11033943 0.76062103]
 [0.551406   0.76724493 0.66955407]
 [0.83401719 0.5591425  0.78634011]]
[[0.26604553 0.14509708 0.95193781 0.44402484 0.73113497 0.88735496]
 [0.93106344 0.11450207 0.63144916 0.92331892 0.04783282 0.23329386]
 [0.29086591 0.52955083 0.55725123 0.79894906 0.06352008 0.20747816]
 [0.0628444  0.20233814 0.11742526 0.17378501 0.76516795 0.34302997]
 [0.09973558 0.52223712 0.77049028 0.55369917 0.11033943 0.76062103]
 [0.10844291 0.72172176 0.28230432 0.551406   0.76724493 0.66955407]
 [0.62629961 0.04373182 0.92417003 0.83401719 0.5591425  0.78634011]]


In [37]:
BB = np.loadtxt("prodm1m2")
print(BB)

[[1.04247333 0.85407745 1.12718048 0.87160121 0.48614529]
 [1.07997798 1.1445512  1.35456546 0.94418088 0.82460023]
 [0.97899066 0.88103544 1.35277216 0.7148203  0.93425092]
 [0.90049161 1.01645652 1.16012478 0.74307843 0.89742146]
 [0.98618837 0.99068164 1.01352339 0.72809433 0.63971206]]
