## Crie um vetor nulo de tamanho 10.

In [15]:
import numpy as np

In [16]:
a = np.empty(10)
print('Vetor nulo de tamanho 10:')
print(a)

Vetor nulo de tamanho 10:
[6.92480604e-310 4.66888190e-310 6.92480623e-310 6.92480620e-310
 6.92480620e-310 6.92480478e-310 6.92480622e-310 6.92477839e-310
 6.92480624e-310 6.92480624e-310]


## Como encontrar o tamanho da memória de qualquer matriz.

In [17]:
print('Criação da matriz: ')
m = np.arange(9).reshape((3,3))
print(m)

Criação da matriz: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
print('Forma 1: comando nbytes')
m.nbytes

Forma 1: comando nbytes


72

In [19]:
print('Forma 2: multiplicação do tamanho de cada item pelo tamanho da matriz')
print('%d bytes' % (m.size * m.itemsize))

Forma 2: multiplicação do tamanho de cada item pelo tamanho da matriz
72 bytes


## Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1.

In [20]:
a = np.empty(10)  # Cria um vetor nulo de tamanho 10
print(a)
a[4] = 1  # Atribui 1 ao quinto item do vetor
print(a)

[6.92480604e-310 4.66888190e-310 6.92480623e-310 6.92480620e-310
 6.92480620e-310 6.92480478e-310 6.92480622e-310 6.92477839e-310
 6.92480624e-310 6.92480624e-310]
[6.92480604e-310 4.66888190e-310 6.92480623e-310 6.92480620e-310
 1.00000000e+000 6.92480478e-310 6.92480622e-310 6.92477839e-310
 6.92480624e-310 6.92480624e-310]


## Crie um vetor com valores que variam de 10 a 49.

In [22]:
print('Vetor com valores entre 10 e 49')
a = np.arange(10, 49)
print(a)

Vetor com valores entre 10 e 49
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## Inverter um vetor (o primeiro elemento se torna o último).

In [28]:
a = np.arange(5)
b = np.flip(a)
print('Vetor:')
print(a)
print('Vetor invertido:')
print(b)

Vetor:
[0 1 2 3 4]
Vetor invertido:
[4 3 2 1 0]


## Crie uma matriz 3x3 com valores que variam de 0 a 8.

In [30]:
a = np.arange(9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Crie uma matriz de identidade 3x3.

In [31]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Crie uma matriz 3x3x3 com valores aleatórios.

In [34]:
a = np.random.random((3, 3, 3))
print(a)

[[[0.2610087  0.43714291 0.01078698]
  [0.57017144 0.54558611 0.8759669 ]
  [0.77227099 0.39371944 0.7425898 ]]

 [[0.7830928  0.79356033 0.54243017]
  [0.89574742 0.36593353 0.51289319]
  [0.69016887 0.55160657 0.92896053]]

 [[0.96442137 0.71214167 0.3018807 ]
  [0.23435296 0.18954081 0.30886908]
  [0.24425691 0.90781582 0.53092791]]]


## Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo.

In [39]:
a = np.random.random((10, 10))
vmax = np.max(a)
vmin = np.min(a)
print('Matriz:')
print(a)
print('Valor máximo: ', vmax)
print('Valor mínimo: ', vmin)

Matriz:
[[0.23484569 0.86164944 0.893006   0.59526989 0.44649681 0.16063151
  0.42412388 0.24229561 0.44749397 0.09776326]
 [0.72440202 0.5949773  0.35842282 0.40352458 0.92747204 0.94800992
  0.29918608 0.79171029 0.20124942 0.81924259]
 [0.7006438  0.3626408  0.08225412 0.34179316 0.67557981 0.29560755
  0.63794658 0.81911705 0.57560921 0.61812002]
 [0.03768613 0.25874423 0.21938571 0.19667005 0.04045102 0.33376112
  0.19720555 0.05208563 0.49109649 0.99169527]
 [0.95856028 0.22039841 0.44466132 0.05089035 0.45738224 0.67730522
  0.60287601 0.91535851 0.49192364 0.87316845]
 [0.35363867 0.94330812 0.11111054 0.11961067 0.83248328 0.82448359
  0.69710622 0.33717439 0.32992672 0.20858805]
 [0.78346849 0.88598311 0.14394691 0.08960189 0.53171892 0.41412201
  0.94434781 0.51421219 0.40352573 0.93787958]
 [0.06883066 0.43387052 0.6455076  0.07606482 0.18040799 0.7808715
  0.41851644 0.34398961 0.84938248 0.24940067]
 [0.72012986 0.99101707 0.15355871 0.35711523 0.31899679 0.29928045
  0.1

## Crie um vetor aleatório de tamanho 30 e encontre o valor médio.

In [44]:
a = np.random.random(30)
meanv = np.mean(a)
print('Matriz: ')
print(a)
print('\n')
print('Média dos valores do vetor: ', meanv)

Matriz: 
[0.27753214 0.48058058 0.35027754 0.52672105 0.52869746 0.65639542
 0.68432054 0.15993173 0.76256951 0.35611535 0.95063599 0.13396131
 0.22427272 0.58894908 0.34414271 0.68909117 0.7902005  0.38788416
 0.42494854 0.13799718 0.31861988 0.39855109 0.61504138 0.33441194
 0.99368461 0.04228271 0.6112295  0.66862464 0.90384152 0.30333946]


Média dos valores do vetor:  0.4881617145470824


## Crie uma matriz 2D com 1 na borda e 0 dentro.

In [34]:
linhas = 10  # Número de linhas da matriz
colunas = 10  # Número de colunas da matriz
m = np.zeros((linhas,colunas))  # Cria uma matriz de zeros
m[0,:] = 1  # Atribui 1 as bordas da matriz
m[:,0] = 1
m[-1,:] = 1
m[:,-1] = 1
print(m)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal.

In [29]:
m = np.zeros((5,5))
m1 = m[1:, 0:]
print(m)
print(m1)
np.fill_diagonal(m1, np.arange(1,5))
print(m1)
print(m)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b).

In [37]:
from PIL import Image

W = 500  # Número de linhas da matriz
h = 300  # Número de colunas da matriz
data = np.random.randint(0, 256, [h,w,3])  # Cria uma matriz  linhas x colunas, onde cada célula
print(data)                                # representa um pixel RGB de cor aleatória
img = Image.fromarray(data, 'RGB')  # Transforma a matriz em uma imagem
img.save('my.png')
img.show()

[[[235 126 114]
  [ 10 241 167]
  [253 246 164]
  ...
  [144 125  32]
  [  4 253  46]
  [110 142 243]]

 [[180   8  66]
  [120 204 135]
  [110 173 188]
  ...
  [146 130 201]
  [ 72 109 168]
  [221 207  18]]

 [[ 30 100 152]
  [107 216 241]
  [ 79 213   7]
  ...
  [150  96 121]
  [206 201 169]
  [217  35 216]]

 ...

 [[219 155  87]
  [161  66 242]
  [132 189  16]
  ...
  [241  88 227]
  [ 21 254 212]
  [ 59 163 204]]

 [[134  48 217]
  [135 127 212]
  [121  80  76]
  ...
  [132   7  53]
  [200 191  94]
  [172 137 249]]

 [[ 96 124 209]
  [197 189 227]
  [163 224 230]
  ...
  [122  50 105]
  [126 219 254]
  [ 67 229  23]]]


## Subtrair a média de cada linha de uma matriz.

In [96]:
m = np.random.randint(0,5,(3,3))
print('Matriz:')
print(m)
print('\n')
print('Média de cada linha da matriz: ')
print(np.average(m, axis=1))
print('\n')
print('Média de todos itens da matriz: ')
print(np.average(m))
print('\n')
print('Matriz com cada a média subtraída de cada item:')
print(m-np.average(m))

Matriz:
[[3 2 2]
 [1 4 3]
 [2 1 0]]


Média de cada linha da matriz: 
[2.33333333 2.66666667 1.        ]


Média de todos itens da matriz: 
2.0


Matriz com cada a média subtraída de cada item:
[[ 1.  0.  0.]
 [-1.  2.  1.]
 [ 0. -1. -2.]]


## Como encontrar o valor mais frequente em uma matriz?

In [120]:
m = np.random.randint(0,3,(3,3))
m = np.ravel(m)
counts = np.bincount(m)
print('Matriz:')
print(m)
print('Elemento mais frequente da matriz:')
print(np.argmax(counts))

Matriz:
[0 1 0 0 1 1 2 0 0]
Elemento mais frequente da matriz:
0


## Crie uma matriz a partir de um arquivo.

In [109]:
np.loadtxt('mymatrix')  # O arquivo deve estar na mesma pasta
                        # ou o caminho do arquivo pode ser apontado.

array([[4., 1., 7.],
       [9., 9., 1.],
       [9., 7., 5.]])

## Crie uma matriz com valores aletaórios e salve para um arquivo.

In [20]:
linhas = 3
colunas = 3
m = np.random.randint(0,10,(linhas,colunas))
np.savetxt('mymatrix', m)

In [21]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])