### Exercícios:

   * Crie um array com 10 elementos usando a função arange

   * Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape

   * Crie duas matrizes bidimensionais com valores aleatórios

   * calcule a transposta de cada matriz

   * multiplique as duas matrizes

   * Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?

   *  Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linh

In [5]:
import numpy as np

In [45]:
#Crie um array com 10 elementos usando a função arange

array = np.array(range(10))
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
#Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape

array = np.array(range(10))
print(array.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [65]:
#Crie duas matrizes bidimensionais com valores aleatórios
m1 = np.random.randint(1,5,(2,2))
m2 = np.random.randint(1,5,(2,2))

# calcule a transposta de cada matriz
t1 = m1.T
t2 = m2.T
print('transposta1')
print(m1)
print(t1)
print('transposta2')
print(m2)
print(t2)

#multiplique as duas matrizes
print('multiplique as duas matrizes')
print (np.multiply(m1,m2))


transposta1
[[3 1]
 [4 2]]
[[3 4]
 [1 2]]
transposta2
[[3 1]
 [2 2]]
[[3 2]
 [1 2]]
multiplique as duas matrizes
[[9 1]
 [8 4]]


In [100]:
#Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?
m1 = np.random.randint(1,5,(2,2))
m2 = np.random.randint(1,5,(2,2))

out = np.multiply(m1,m2)
def write(file, m, name):
    with open(file, 'a') as f:
        f.write('%s\n'%name)
        np.savetxt(f, m, fmt='%.0f')
        f.write('\n')
        
    print('done writing')
write('text.txt', m1, 'mat1')
write('text.txt', m2, 'mat2')

write('text.txt', out, 'outup')
!cat 'text.txt'

done writing
done writing
done writing
mat1
3 4
2 2

mat2
2 3
3 2

outup
6 12
6 4



In [123]:
#Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha

a1 = np.random.randint(1,3,(2,2))
a2 = np.random.randint(1,3,(2,2))
print(a1)
print('\n')
print(a2)
print('\nconcatenate')
b = np.concatenate((a1,a2), axis=1)
print(b)


[[1 1]
 [1 2]]


[[1 2]
 [1 2]]

concatenate
[[1 1 1 2]
 [1 2 1 2]]


## list 2
  *  Crie um vetor nulo de tamanho 10
  * Como encontrar o tamanho da memória de qualquer matriz
  * Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
  * Crie um vetor com valores que variam de 10 a 49
  * Inverter um vetor (o primeiro elemento se torna o último)
  * Crie uma matriz 3x3 com valores que variam de 0 a 8
  * Crie uma matriz de identidade 3x3
  *  Crie uma matriz 3x3x3 com valores aleatórios
  *  Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
  * Crie um vetor aleatório de tamanho 30 e encontre o valor médio
  *  Crie uma matriz 2D com 1 na borda e 0 dentro
  *  Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
  *  Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
  *  Subtrair a média de cada linha de uma matriz
  * Como encontrar o valor mais frequente em uma matriz?
  * Crie uma matriz a partir de um arquivo
  * crie uma matriz com valores aletaórios e salve para um arquivo



In [126]:
#Crie um vetor nulo de tamanho 10

vecnull = np.zeros(10)
print(vecnull)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Como encontrar o tamanho da memória de qualquer matriz



In [150]:
#Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

vecnull_1 = np.zeros(10)
print(vecnull1)
vecnull_1[-1] = 1
print(vecnull_1)

#Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
vecnull_1[4] = 1
print(vecnull_1)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


In [155]:
#Crie um vetor com valores que variam de 10 a 49
val = np.random.randint(range(10,49))
print(val)

[ 1  1  8  3  1  8  4 11  2  8  9 17 11  4 13  4 10  2 27 19  3  9 10 23
 18  2  0 25 21 22  5 18 13 25 29 30 19 39  8]


In [158]:
#Inverter um vetor (o primeiro elemento se torna o último)
verse = np.random.randint(range(10,34))
print(verse)
print(verse[::-1])

[ 3  9  7  8  3  0  6  2  0  4 19 13  0 22  3 22 10  4 25 22  6 19 12  1]
[ 1 12 19  6 22 25  4 10 22  3 22  0 13 19  4  0  2  6  0  3  8  7  9  3]


In [159]:
#Crie uma matriz 3x3 com valores que variam de 0 a 8
mat3 = np.random.randint(0,8,(3,3))
print(mat3)

[[2 3 0]
 [2 1 4]
 [4 4 4]]


In [161]:
#Crie uma matriz de identidade 3x3
id3 = np.identity(3)
print(id3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [163]:
#Crie uma matriz 3x3x3 com valores aleatórios

ale3x3x3 = np.random.randint(0,50,(3,3,3))

print(ale3x3x3)

[[[21 31 18]
  [43 23  1]
  [ 0 21  8]]

 [[ 8 43  4]
  [40 38 30]
  [32 41 49]]

 [[32 48 23]
  [14  1  9]
  [42 41 47]]]


In [167]:
#Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

ale10x10 = np.random.randint(4,8,(10,10))
print(ale10x10)
maxl = ale10x10.max()
minl = ale10x10.min()
print(maxl, 'max')
print(minl, 'min')

[[4 6 4 6 5 5 4 7 7 6]
 [6 6 4 4 7 5 5 4 4 7]
 [5 6 7 4 5 7 7 7 4 5]
 [6 5 7 4 7 4 6 5 6 7]
 [4 5 7 5 7 4 7 7 4 7]
 [4 4 5 4 7 4 6 5 6 5]
 [6 4 4 7 4 6 7 6 7 5]
 [5 4 5 4 6 7 4 4 6 5]
 [7 6 6 5 5 6 6 5 4 4]
 [6 4 5 7 6 7 4 7 6 7]]
7 max
4 min


In [179]:
#Crie um vetor aleatório de tamanho 30 e encontre o valor médio
med = np.random.randint(1,3,(30))
print(med)
print(med.mean())

[2 2 2 2 1 2 1 2 1 1 2 1 2 2 2 2 2 1 1 1 1 1 1 1 2 2 1 2 2 1]
1.5333333333333334


In [250]:
#Crie uma matriz 2D com 1 na borda e 0 dentro
# Creates a list containing 5 lists, each of 8 items, all set to 0
cols, rows = 5, 5;
z = np.array([[1 for x in range(cols)] for y in range(rows)])

z[1:-1,1:-1] = 0
print(z)
d = np.ones((5,5), dtype=int)

print('\n')
d[1:-1,1:-1] = 0
print(d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [276]:
#Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
n = np.identity(5)
rng = np.arange(1,5)
n[rng, rng-1] = rng
print(n)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


In [6]:
#Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
z = np.zeros((5,5))
rng = np.arange(4)
z[rng, rng+1] = np.sqrt(rng+1)
print(z)

[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]


In [15]:
#Subtrair a média de cada linha de uma matriz
med = np.random.randint(1,3,(2,2))
print(med)
m1 = med - med.mean(axis=1, keepdims=True) 
m1

[[1 1]
 [1 2]]


array([[ 0. ,  0. ],
       [-0.5,  0.5]])

In [33]:
#Como encontrar o valor mais frequente em uma matriz?
import numpy as np

matrix = np.random.randint(1,10,(3,3))
print(matrix)
vec = []
for i in matrix:
    for j in i:
        vec.append(j)
print(vec)
a = np.bincount(vec)
modes = np.argwhere(a == np.amax(a))
#mode = np.argmax(np.bincount(vec))
print(modes.tolist())

[[1 8 9]
 [6 8 9]
 [6 1 2]]
[1, 8, 9, 6, 8, 9, 6, 1, 2]
[[1], [6], [8], [9]]


In [231]:
import numpy as np
from scipy import stats

a = np.array([[1, 3, 4, 2, 2, 7],
              [5, 2, 2, 1, 4, 1],
              [3, 3, 2, 2, 1, 1]])
b = np.random.randint(1,10,(3,3))
print(b)
m = stats.mode(b, axis=None)
print(m)

[[9 2 6]
 [4 2 8]
 [3 6 9]]
ModeResult(mode=array([2]), count=array([2]))


In [72]:
#Crie uma matriz a partir de um arquivo
s = []
f = open('matrix_to_file.txt')
for i in f:
    s.append(i.strip().split())
s= np.asarray(s).astype(np.float)
print(s)

[[5. 9. 7.]
 [5. 8. 1.]
 [4. 1. 5.]]


In [62]:
#crie uma matriz com valores aletaórios e salve para um arquivo
filematrix = np.random.randint(1,10,(3,3))
print(filematrix)
np.savetxt('matrix_to_file.txt',filematrix, fmt='%.1f')
!cat matrix_to_file.txt

[[5 9 7]
 [5 8 1]
 [4 1 5]]
5.0 9.0 7.0
5.0 8.0 1.0
4.0 1.0 5.0


In [17]:
from scipy.signal import convolve2d

a = (convolve2d(np.ones((5,5)), np.ones((3,3)),'same')==0)+-1

print(a)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [20]:
matrix = np.random.randint(1,10,(3,3))
vec = [[i for i in j] for j in matrix]
print(matrix)
print(vec)

#[entry for tag in tags for entry in entries if tag in entry]

[[2 1 5]
 [6 6 6]
 [1 7 3]]
[[2, 1, 5], [6, 6, 6], [1, 7, 3]]
