### Exercícios Numpy
* Crie um vetor nulo de tamanho 10
* Como encontrar o tamanho da memória de qualquer matriz
* Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
* Crie um vetor com valores que variam de 10 a 49
* Inverter um vetor (o primeiro elemento se torna o último)
* Crie uma matriz 3x3 com valores que variam de 0 a 8
* Crie uma matriz de identidade 3x3
* Crie uma matriz 3x3x3 com valores aleatórios
* Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
* Crie um vetor aleatório de tamanho 30 e encontre o valor médio
* Crie uma matriz 2D com 1 na borda e 0 dentro
* Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
* Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
* Subtrair a média de cada linha de uma matriz
* Como encontrar o valor mais frequente em uma matriz?
* Crie uma matriz a partir de um arquivo
* Crie uma matriz com valores aletaórios e salve para um arquivo

In [3]:
import numpy as np

In [3]:
#1. crie um vetor nulo de tamanho 10
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#2. como encontrar o tamanho da memória de qualquer matriz

In [5]:
#3. crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
n = np.zeros(10)
n[4] = 1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#4. crie um vetor com valores que variam de 10 a 49
n = np.arange(10,50)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
#5. inverter um vetor (o primeiro elemento se torna o último)
m = np.arange(10)
n = np.flip(np.arange(10), 0)
print(m)
print(n)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [30]:
#6. crie uma matriz 3x3 com valores que variam de 0 a 8
n = np.arange(9).reshape(3,3)
print(n)

8
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [18]:
# 7. crie uma matriz de identidade 3x3
n = np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# 17. crie uma matriz 3x3x3 com valores aleatórios
n = np.random.rand(27).reshape(3,3,3)
print(n)

[[[0.96813591 0.19829938 0.84917003]
  [0.72189402 0.31083023 0.34577843]
  [0.65364023 0.84474398 0.83960724]]

 [[0.68814586 0.26732452 0.97529904]
  [0.59353565 0.52356139 0.31785916]
  [0.48862378 0.29983377 0.14517229]]

 [[0.72242942 0.84042654 0.83397337]
  [0.55764711 0.67502919 0.51333879]
  [0.60302996 0.28709633 0.37531046]]]


In [6]:
#9. crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
n = np.random.rand(100).reshape(10,10)
print(np.amin(n))
print(np.amax(n))

0.005156194260415803
0.9981821652103645


In [44]:
#10. crie um vetor aleatório de tamanho 30 e encontre o valor médio
n = np.arange(30)
print('O vetor é:', n)
print('A média do vetor acima é', np.mean(n))

O vetor é: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
A média do vetor acima é 14.5


In [67]:
#11. crie uma matriz 2D com 1 na borda e 0 dentro
n = np.ones((4,4))
n[1:-1,1:-1] = 0
print(n)
print('')

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]



In [22]:
#12. crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
n = np.diag(np.arange(4)+1,k=-1)
print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [100]:
#13. crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
def rgb_matrix(x,y):
    return

In [16]:
#14. subtrair a média de cada linha de uma matriz
n = np.random.randint(10, size=(2,2))
print(n)
print('')

#numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
#Axis or axes along which the means are computed. The default is to compute the mean of the flattened array.
#If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.
m = n - n.mean(axis=1, keepdims=True)
print(m)


[[0 7]
 [1 4]]

[[-3.5  3.5]
 [-1.5  1.5]]


In [52]:
#15. como encontrar o valor mais frequente em uma matriz?
n = np.random.randint(1, 10, (5,5))
print('matriz:')
print(n)
print('')

lista = []
for i in n:
    for j in i:
        lista.append(j)

print('lista:')        
print(lista)
print('')
print('np.bincount:')
nc = np.bincount(lista)
print(list(nc))

modas = np.argwhere(np.bincount(lista) == np.amax(np.bincount(lista)))

print(np.argmax(np.bincount(lista)))

print(modas)

matriz:
[[8 6 4 5 9]
 [6 5 3 9 7]
 [1 8 8 4 9]
 [6 2 4 9 1]
 [6 8 5 4 7]]

lista:
[8, 6, 4, 5, 9, 6, 5, 3, 9, 7, 1, 8, 8, 4, 9, 6, 2, 4, 9, 1, 6, 8, 5, 4, 7]

np.bincount:
[0, 2, 1, 1, 4, 3, 4, 2, 4, 4]
4
[[4]
 [6]
 [8]
 [9]]


In [40]:
#15. como encontrar o valor mais frequente em uma matriz?
#fazendo uso do scipy
from scipy import stats
n = np.random.randint(1, 10, (3,3))
print(n)
nc=stats.mode(n, axis=None)
print(nc)

[[3 4 3]
 [8 2 7]
 [6 9 7]]
ModeResult(mode=array([3]), count=array([2]))


In [26]:
#16. crie uma matriz a partir de um arquivo
#f = open('matrix16.txt', 'w')
f = open('/home/cavalcante87/Documents/fiephub/matrix16.txt', 'r')

lista = []
for i in f:
    lista.append(i.strip().split())
print(lista)

nova_lista = np.asarray(lista).astype(np.int)

print('')

print(nova_lista)

[['1', '5', '8'], ['4', '5', '1'], ['8', '5', '8']]

[[1 5 8]
 [4 5 1]
 [8 5 8]]


In [21]:
#17. crie uma matriz com valores aleatórios e salve para um arquivo
n = np.random.randint(1,10,(3,3))
np.savetxt('/home/cavalcante87/Documents/fiephub/matrix16.txt', n, fmt='%.0f')
!cat '/home/cavalcante87/Documents/fiephub/matrix16.txt'

1 5 8
4 5 1
8 5 8
