# Numpy Exercícios

In [2]:
import numpy as np

##    Crie um vetor nulo de tamanho 10

In [35]:
v = np.zeros(10,dtype=np.int16)
print(v)

[0 0 0 0 0 0 0 0 0 0]


##    Como encontrar o tamanho da memória de qualquer matriz

In [37]:
print("Memory size: %d bytes" % (v.size*v.itemsize))

Memory size: 240 bytes


##    Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

In [51]:
v = np.zeros(10)
v[4]=1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


##    Crie um vetor com valores que variam de 10 a 49

In [6]:
v = np.arange(10,50,1)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


##    Inverter um vetor (o primeiro elemento se torna o último)

In [8]:
iv = np.flip(v)
print(iv)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


##    Crie uma matriz 3x3 com valores que variam de 0 a 8

In [25]:
v = np.random.randint(9,size=(3,3))
print(v)

[[7 5 7]
 [0 5 1]
 [4 7 8]]


##    Crie uma matriz de identidade 3x3

In [7]:
i = np.identity(3,dtype=np.int16)
e = np.eye(3,dtype=np.int16)
print(i)
print(e)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


##    Crie uma matriz 3x3x3 com valores aleatórios

In [22]:
a = np.random.randint(100,size=(3,3,3))
print(a)

[[[66  4 52]
  [54 74  2]
  [ 2  2 83]]

 [[ 3 47 40]
  [22  4 87]
  [46 48 88]]

 [[25  8 27]
  [85 11 71]
  [64 37 58]]]


##    Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

In [28]:
a = np.random.randint(100,size=(10,10))
print(a)
print("Minimo: ",np.amin(a))
print("Maximo: ",np.amax(a))

[[77 49  0 41 97  4 38 60 89 10]
 [ 8 19 97 88 75  6 39  3 50 36]
 [26 27 14 33 91 54 50  3 55 99]
 [54 26 79 80 51 17 75 68 92 20]
 [ 3 10 77 14 12 21 79 95 82 16]
 [38 50 94 53 84 72 85 46 49 75]
 [40 96 79 21 64 65 84 37 76  2]
 [31 72 27 18  9 97 45 58 92 78]
 [19 35 34 64 55 42 87 73 39 78]
 [67 63 12 86 80 38 35 71 64 45]]
Minimo:  0
Maximo:  99


##    Crie um vetor aleatório de tamanho 30 e encontre o valor médio

In [36]:
v = np.random.random(30)
print(v)
m = np.mean(v)
print("Media: ",m)

[0.92925178 0.82107023 0.01420986 0.29913798 0.49806444 0.75126924
 0.30936061 0.45967971 0.95268059 0.33075927 0.09969415 0.97549728
 0.83065997 0.27728577 0.91945569 0.08645406 0.38818239 0.99928009
 0.53269819 0.53089476 0.45249122 0.44592286 0.77522853 0.0657488
 0.63961603 0.25379475 0.21050757 0.69012113 0.67487508 0.74808169]
Media:  0.5320657908918748


##    Crie uma matriz 2D com 1 na borda e 0 dentro

In [39]:
m = np.ones((6,6))
m[1:-1,1:-1]=0
print(m)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


##    Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal

In [71]:
m = np.diag(1+np.arange(4),k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


##    Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

In [5]:
m = np.ones((3,3), [ ('posicao', [ ('x', float, 1), ('y', float, 1)] ),
                   ('cor',    [ ('r', float, 1), ('g', float, 1),
                               ('b', float, 1)])])
print(m)

[[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.))]
 [((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.))]
 [((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
  ((1., 1.), (1., 1., 1.))]]


## Subtrair a média de cada linha de uma matriz

In [81]:
matriz = np.random.randint(10,size=(4,4))
print(matriz)
media = np.mean(matriz,axis=1).astype(int)
print(media)

for l,n in zip(matriz,media):
    l -= n
    
print(matriz)


[[2 0 2 2]
 [7 3 5 2]
 [9 9 1 3]
 [5 1 1 8]]
[1 4 5 3]
[[ 1 -1  1  1]
 [ 3 -1  1 -2]
 [ 4  4 -4 -2]
 [ 2 -2 -2  5]]


##    Como encontrar o valor mais frequente em uma matriz?

In [56]:
a = np.array([1,2,2,2,4,5,2,1])
c = np.bincount(a)
print(np.argmax(c))

2


##    Crie uma matriz a partir de um arquivo

In [60]:
m = np.load("matriz.npy")
print(m)

[[44 41 21 74 61 73 28 79 64 41]
 [81  3 63 67 75 41 75 45 25 78]
 [ 1 63 44 89 42 65 71 16 94 38]
 [89  7  1  4  0 69 40 81 43 99]
 [83 33 17 83 48 53  2 19 90 11]
 [67 29 92 85 42 43 10 17 31 68]
 [57 79 94  7 68 63 82 73 56 59]
 [90 27 25 26 58 88 83 99 66 62]
 [34 41 86 93 15 92 65 80  5 19]
 [37 82 57 90 48 88 98 18 29 38]]


##    Crie uma matriz com valores aleatórios e salve para um arquivo

In [58]:
m = np.random.randint(100,size=(10,10))
np.save('matriz',m)