## Exercícios

* Crie um vetor nulo de tamanho 10  
* Como encontrar o tamanho da memória de qualquer matriz  
* Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1  
* Crie um vetor com valores que variam de 10 a 49
* Inverter um vetor (o primeiro elemento se torna o último)
* Crie uma matriz 3x3 com valores que variam de 0 a 8
* Crie uma matriz de identidade 3x3
* Crie uma matriz 3x3x3 com valores aleatórios
* Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
* Crie um vetor aleatório de tamanho 30 e encontre o valor médio
* Crie uma matriz 2D com 1 na borda e 0 dentro
* Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
* Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
* Subtrair a média de cada linha de uma matriz
* Como encontrar o valor mais frequente em uma matriz?
* Crie uma matriz a partir de um arquivo
* Crie uma matriz com valores aletaórios e salve para um arquivo

In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

print("\nVetor de nulos\n", np.zeros(10))

print("\nTamanho da memória de uma matriz\n", np.zeros(10).nbytes)

v = np.zeros(10)
v[5] = 1
print("\nVetor de nulos com posição i alterada\n", v)

print("\nVetor de valores entre 10 e 49\n", np.arange(10, 50, 1))

print("\nVetor intertido\n", np.flip(np.arange(10, 50, 1)))

print("\nMatriz sequencial de 0 a 8\n", np.arange(0, 9, 1).reshape((3,3)))

print("\nMatriz identidade\n", np.identity(3))

print("\nMatriz 3x3 de valores aleatórios\n", np.random.random((3,3,3)))

m = np.random.randint(0, 100, (10,10))
print("\nMatriz 10x10\n", m)
print("\nMínimo e máximo da matriz 10x10: %.2f : %.2f\n" % (m.min(), m.max()))

v = np.random.random(30)
print("\nVetor de 30 elementos\n", v)
print("\nMédia do vetor\n", v.mean())

m = np.zeros((5,5))
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        if (i==0 or i==m.shape[0]-1) or (j==0 or j==m.shape[1]-1): m[i,j] = 1
print("\nMatriz 2D com borda\n", m)

m = np.zeros((5,5))
m[0], m[m.shape[0]-1], m[:,0], m[:,m.shape[1]-1] = 1, 1, 1, 1
print("\nMatriz 2D com borda inteligente\n", m)

n = 10
m = np.concatenate((np.zeros((1,n)),np.arange(1,n+1)*np.identity(n)), axis=0)
m = np.delete(m, m.shape[1], axis=0)
print("\nMatriz doidona\n", m)

def modify(m, r, c, ch):
    for i in range(r):
        for j in range(c):
            m[i,j,ch] = 255 if i % (j+1) < 5 and i % (j+1) > -5 else m[i,j,ch]
            m[i,j,1] = m[i,j,1] * 255
            m[i,j,1] = 255 if i == j else m[i,j,1]
            m[i,j,2] = j * m[i,j,2] * 255
    return m
f = np.full((800, 1200, 3), 1)
f = modify(f, f.shape[0], f.shape[1], 0)   
print("\nFoto\n", f)
from PIL import Image
img = Image.fromarray(f.astype('uint8'), 'RGB')
img.show()

m = np.random.random((3, 5))
print("\nMatriz antes da subtração\n", m)
print("\nMédia de cada linha\n", np.mean(m, axis=1))
m = m - np.mean(m, axis=1).reshape((m.shape[0], 1))
print("\nMatriz após a subtração\n", m)

from scipy import stats
m = np.random.randint(0, 100, (3,10))
print("\nMatriz para analisar moda\n", m)
print("\nModa desta matriz\n", np.argmax(np.bincount(m.flatten())))

print("\nMatriz a partir do arquivo\n", np.loadtxt('dados.txt'))

m = np.random.random((100,30))
np.savetxt('dados.txt', m)
print("\nMatriz salva para o arquivo\n")


Vetor de nulos
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Tamanho da memória de uma matriz
 80

Vetor de nulos com posição i alterada
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]

Vetor de valores entre 10 e 49
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Vetor intertido
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]

Matriz sequencial de 0 a 8
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Matriz identidade
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz 3x3 de valores aleatórios
 [[[0.8667 0.0871 0.571 ]
  [0.2429 0.0755 0.397 ]
  [0.5527 0.4286 0.0162]]

 [[0.5319 0.0037 0.5201]
  [0.5524 0.6468 0.4279]
  [0.0482 0.527  0.686 ]]

 [[0.1109 0.4769 0.4756]
  [0.7666 0.4862 0.5826]
  [0.878  0.2139 0.1089]]]

Matriz 10x10
 [[22  6 50 78  5  5 59 47 67 33]
 [95 52  0 89 80 94 15 54 85 85]
 [66 69 38 81 56 64 47 72 93 44]
 [40 76 33 28 37 13 66 42 96 52]
 [76 63 68 96 38 