In [3]:
import numpy as np

In [16]:
#Create matrix 10 indices com elementos 0

#n_1 = numpy.empty(10) # Cria matrix com valores arbitrarios
n_2 = numpy.zeros(10)
print(n_2)
print(n_2.itemsize) # Tamanho do elemento em bytes

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8


In [17]:
#Add 1 na quinta posicao da matrix
n_2[4] = 1
print(n_2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [21]:
#Create a matrix with elements betwenn 10 and 49
n_3 = np.arange(10,50)
print(n_3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
#Inverter matrix
n_4 = np.flip(n_3)
print(n_4)
#print(n_3[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [31]:
#Criar matrix 3x3

n_5 = np.arange(0,9).reshape(3,3)
print(n_5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
#Criar matrix identidade

n_6 = np.identity(3)
print(n_6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
#Criar matrix 3x3x3

n_7 = np.ndarray(shape=(3,3,3))
print(n_7)

[[[4.67092658e-310 2.31297541e-312 9.97338022e-313]
  [2.14321575e-312 2.14321575e-312 2.37663529e-312]
  [9.97338022e-313 2.35541533e-312 2.33419537e-312]]

 [[2.35541533e-312 2.12199579e-312 9.97338022e-313]
  [2.35541533e-312 2.12199579e-312 9.97338022e-313]
  [2.33419537e-312 2.44029516e-312 1.46417710e-312]]

 [[2.50395503e-312 9.97338022e-313 2.22809558e-312]
  [9.97338022e-313 2.56761491e-312 2.20687562e-312]
  [2.33419537e-312 0.00000000e+000 0.00000000e+000]]]


In [42]:
#Criar matrix 10x10 e encontrar o maior valor

n_8 = np.ndarray(shape=(10,10))
n_8[0][0] = 3
print(numpy.amax(n_8))
print(n_8)

3.0
[[3.00000000e+000 2.25293935e-321 0.00000000e+000 4.67092712e-310
  4.94065646e-324 4.67092712e-310 4.94065646e-324 4.67092712e-310
  4.67072494e-310 6.89963286e-310]
 [6.89945711e-310 6.89945711e-310 4.94065646e-324 1.38338381e-322
  6.89965990e-310 6.89945711e-310 4.94065646e-324 1.27319747e-313
  1.27319748e-313 4.67092712e-310]
 [6.89965969e-310 6.89945711e-310 1.27319747e-313 0.00000000e+000
  0.00000000e+000 4.94065646e-324 4.67092712e-310 9.88131292e-324
  4.67092712e-310 4.67092712e-310]
 [4.67072494e-310 4.67092524e-310 3.60739284e-313 9.88131292e-324
  5.09278990e-313 4.67072494e-310 4.67092524e-310 4.67092524e-310
  6.89963286e-310 5.72938864e-313]
 [5.09278990e-313 6.89963288e-310 4.67072494e-310 4.94065646e-323
  5.09278990e-313 6.89966196e-310 4.67092712e-310 4.67072494e-310
  4.67092712e-310 4.67092712e-310]
 [4.67092712e-310 1.27319747e-313 4.67072494e-310 4.67092712e-310
  4.67092712e-310 4.67092712e-310 4.67092712e-310 1.27319747e-313
  4.94065646e-324 4.67072494e

In [45]:
#30 elementos, encontre o valor medio


n_9 = np.random.random(30)
print(np.median(n_9))
print(n_9)

0.47967187068221895
[0.74614478 0.47457477 0.65608717 0.37799415 0.85572474 0.48476897
 0.7565204  0.643827   0.29338413 0.35699495 0.72580923 0.71309016
 0.68043103 0.23677323 0.68068838 0.08617935 0.30037631 0.44404967
 0.42507907 0.87284627 0.06417462 0.72692252 0.47299943 0.52133145
 0.64864287 0.47052165 0.73838657 0.27661292 0.09166945 0.12404233]


In [47]:
n_10 = np.array([[1,1,1],[1,0,1],[1,1,1]])
print(n_10)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [71]:

#Criar matrix 2D onde as bordas sao valor 1 e o resto e 0

n1 = int(input("coloque seu numero :" ))
n_11 = np.ndarray(shape=(n1,n1))
for i in range(1, n1-1):
    for j in range(1,n1-1):
        if i == j:
            n_11[i][j] = 0
        else:
            n_11[i][j] = 0
    n_11[0] = 1
    n_11[n1-1] = 1
    n_11[i][0] = 1
    n_11[i][n1-1] = 1
    #for j in range(0,n1):
        #if i>0:
            ## n_11[i][j] = 0
print(n_11)    

coloque seu numero : 10


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [86]:
#Criar matrix 5x5 com valores 1,2,3,4 logo abaixo da diagonal

n2 = int(input("coloque seu numero:" ))
n_12 = np.ndarray(shape=(n2,n2))
for i in range(0,n2):
    for j in range(0, n2):
        if i==j and j>0:
            n_12[i][j-1] = i
        
print(n_12)


coloque seu numero: 10


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 2. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 3. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 4. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 5. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 6. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 7. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 8. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 9. 1.]]


In [91]:
#Matrix NxNxN

n4 = int(input("Numero de Linhas: "))
n5 = int(input("Numero de colunas: "))
n3 = int(input("Numero de matrizes: "))
n_13 = np.ndarray(shape=(n3,n4,n5))
print(n_13)

Numero de Linhas:  3
Numero de colunas:  3
Numero de matrizes:  3


[[[4.67092658e-310 2.31297541e-312 9.97338022e-313]
  [2.14321575e-312 2.14321575e-312 2.37663529e-312]
  [9.97338022e-313 2.35541533e-312 2.33419537e-312]]

 [[2.35541533e-312 2.12199579e-312 9.97338022e-313]
  [2.35541533e-312 2.12199579e-312 9.97338022e-313]
  [2.33419537e-312 2.44029516e-312 1.46417710e-312]]

 [[2.50395503e-312 9.97338022e-313 2.22809558e-312]
  [9.97338022e-313 2.56761491e-312 2.20687562e-312]
  [2.33419537e-312 0.00000000e+000 0.00000000e+000]]]


In [101]:
#Somar linha 
n6 = int(input("numero de linhas:" ))
n7 = int(input("numero de colunas:"))
n_14 = np.ndarray(shape=(n6,n7))
for i in range(0,n6):
    n_15 = np.sum(n_14[i])/n6
    print(n_15)
print(n_14)

numero de linhas: 10
numero de colunas: 10


1.0
0.2
0.4
0.5
0.6
0.7
0.8
0.9
1.0
1.8
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 2. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 3. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 4. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 5. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 6. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 7. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 8. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 9. 1.]]


In [124]:
#Valores comuns em uma matrix
n_16 = np.array([1,1,2,3,3,4,4,5,6,6])

contador={}
for i in n_16:
    if i not in contador:
        contador[i] = 1
    else:
        contador[i] += 1

print(contador)

{1: 2, 2: 1, 3: 2, 4: 2, 5: 1, 6: 2}


In [15]:
#Media das linhas


a = int(input("numero de linhas: "))
b = int(input('numero de colunas: '))
n_17 = np.random.rand(a,b)
print('Matrix gerada: ',n_17)
for i in range(0, a-1):
    print('media do eixo', i,np.mean(n_17, axis = i))

numero de linhas:  3
numero de colunas:  3


Matrix gerada:  [[0.61773098 0.35128796 0.13966167]
 [0.40108015 0.90490009 0.24691505]
 [0.28885378 0.65931166 0.2860316 ]]
media do eixo 0 [0.4358883  0.63849991 0.22420277]
media do eixo 1 [0.3695602  0.51763176 0.41139901]


In [20]:
#Valor mais frequente 2.0
a = int(input("numero de linhas: "))
b = int(input('numero de colunas: '))
n_18 = np.random.rand(a,b)
n_19_1, n_19 = np.unique(n_18, return_counts=True)
print(np.asarray((n_19_1,n_19)))

numero de linhas:  100
numero de colunas:  100


[[4.03327413e-05 1.54410339e-04 4.75281449e-04 ... 9.99674548e-01
  9.99679974e-01 9.99697085e-01]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 ... 1.00000000e+00
  1.00000000e+00 1.00000000e+00]]
