In [6]:
import numpy as np

In [11]:
n1 = np.arange(10)
print(n1)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
print(n1.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
n2 = np.random.random(8).reshape(2,4)
n3 = np.random.random(8).reshape(2,4)
print(n2, n3)

[[0.43868813 0.60294221 0.22634476 0.68991315]
 [0.35120051 0.13693079 0.83506904 0.51377292]] [[0.13675275 0.08596641 0.56680246 0.91660804]
 [0.13674448 0.37566511 0.04497247 0.50571677]]


In [32]:
n4 = np.transpose(n2)
n5 = np.transpose(n3)
print(n4, n5)

[[0.43868813 0.35120051]
 [0.60294221 0.13693079]
 [0.22634476 0.83506904]
 [0.68991315 0.51377292]] [[0.13675275 0.13674448]
 [0.08596641 0.37566511]
 [0.56680246 0.04497247]
 [0.91660804 0.50571677]]


In [36]:
np.prod(n4,n5)

TypeError: only integer scalar arrays can be converted to a scalar index