## Lista Numpy

* Crie um vetor nulo de tamanho 10

In [ ]:
import numpy as np

print(np.zeros(10))

* Como encontrar o tamanho da memória de qualquer matriz

Matrix_exemplo = np.matrix(np.arange(25).reshape(5,5))
print("Pelo comando 'nomedamatriz.itemsize' podemos determinar o tamanho em bytes, como o exemplo: \n \n", Matrix_exemplo, "\n \n o qual seu tamanho em bytes eh:", Matrix_exemplo.itemsize,"bytes.")


* Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

In [ ]:
vetor = np.zeros(10)
vetor[4] = 1 
print(vetor)

* Crie um vetor com valores que variam de 10 a 49

In [ ]:
Matrix_exemplo = np.arange(10,50)
print(Matrix_exemplo)

* Inverter um vetor (o primeiro elemento se torna o último)

In [ ]:
matrix_exemplo = np.arange(10,50)
print(matrix_exemplo)



* Inverter um vetor (o primeiro elemento se torna o último)

* Crie uma matriz 3x3 com valores que variam de 0 a 8

In [ ]:
print(np.arange(0,9).reshape(3,3))

* Crie uma matriz de identidade 3x3

In [ ]:
print(np.eye(3,3))

* Crie uma matriz 3x3x3 com valores aleatórios

In [ ]:
print(np.random.rand(3,3,3))

* Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

In [ ]:
a = np.random.rand(10,10)
print("matriz: \n \n", a, "\n \n")
print("valor minimo", np.min(a))
print("valor maximo:" , np.max(a))

* Crie um vetor aleatório de tamanho 30 e encontre o valor médio

In [ ]:
a = np.random.rand(30)
print("vetor: \n \n", a, "\n \n")
print("media: \n \n", np.mean(a), "\n \n")


* Crie uma matriz 2D com 1 na borda e 0 dentro

In [47]:
a = np.ones((2,3,4),dtype = np.int16)


a[0][1][1] = 0
a[0][1][2] = 0
a[1][1][1] = 0
a[1][1][2] = 0
print(a)

[[[1 1 1 1]
  [1 0 0 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 0 0 1]
  [1 1 1 1]]]


* Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal

In [51]:


a = np.arange(5)

n = np.diag(np.arange(1,5),k = -1)  #k = 1 altera a diagonal secundaria debaixo

print(n)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


* Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

In [36]:
n = np.array(0,[('posicao', [ ('x', float), ('y', float)]),
                ('cor',     [ ('r', float), ('g', float), ('b', float)])])


# Subtrair a média de cada linha de uma matriz
n = np.random.randint(0,10,(3,4))

'''Formato n.mean():
(eixo do array, keepdims=True), onde keepdims=True informa que o resultado
sera salvo num vetor (linha ou coluna) de forma que permita operacoes posteriores
 '''

m = n - n.mean(axis = 1, keepdims = True)
print(m)


[[-3.   0.   3.   0. ]
 [ 0.5  2.5  1.5 -4.5]
 [ 1.  -1.   1.  -1. ]]


* Como encontrar o valor mais frequente em uma matriz?


In [78]:
#funcao bitcount conta a ocorrencia de cada elemento e retorna em vetor. 
#Funcao argmax retorna o maior valor com maior frequencia dentro de bitcount

n = np.random.randint(1,4,4)
print(n)
print("Valor mais frequente:", np.bincount(n).argmax())

[2 1 1 1]
Valor mais frequente: 1


* crie uma matriz com valores aletaórios e salve para um arquivo

In [112]:
#criando a matriz com valores inteiros aleatorios
n = np.random.randint(1,101,101) 

#para conferir o tamanho da matriz
print(n.shape)

#para salvar a matriz no formato txt
np.savetxt("n.txt",n)  

#para ler o arquivo salvo em txt
np.genfromtxt("n.txt")

#salvando o valor em um arquivo py
np.save("arquivo", n)



(101,)
