In [88]:
import numpy as np

#Crie um vetor nulo de tamanho 10
print("Crie um vetor nulo de tamanho 10")
vetorNulo = np.ndarray(10)
print(vetorNulo)

#Como encontrar o tamanho da memória de qualquer matriz
print("Como encontrar o tamanho da memória de qualquer matriz")
print("%d bytes" % (vetorNulo.size * vetorNulo.itemsize))

#Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
print("Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1")
vetorNulo = np.ndarray(10)
vetorNulo[5] = 1
print(vetorNulo)

#Crie um vetor com valores que variam de 10 a 49
print("Crie um vetor com valores que variam de 10 a 49")
vetorNulo = np.arange(10, 49)
print(vetorNulo)

#Inverter um vetor (o primeiro elemento se torna o último)
print("Inverter um vetor (o primeiro elemento se torna o último)")
print(vetorNulo[::-1])

#Crie uma matriz 3x3 com valores que variam de 0 a 8
print("Crie uma matriz 3x3 com valores que variam de 0 a 8")
vetorNulo = np.random.randint(8, size=(3,3))
print(vetorNulo)

#Crie uma matriz de identidade 3x3
print("Crie uma matriz de identidade 3x3")
matrizNormal = np.eye(3)
print(matrizNormal)

#Crie uma matriz 3x3x3 com valores aleatórios
print("Crie uma matriz 3x3x3 com valores aleatórios")
vetorNulo = np.random.random(size=(3,3,3))
print(vetorNulo)

#Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
print("Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo")
vetorNulo = np.random.random(size=(3,3))
print("Max ", vetorNulo.max())
print("Min ", vetorNulo.min())

#Crie um vetor aleatório de tamanho 30 e encontre o valor médio
print("Crie um vetor aleatório de tamanho 30 e encontre o valor médio")
vetorNulo = np.ndarray((30,30))
print(vetorNulo.mean())

#Crie uma matriz 2D com 1 na borda e 0 dentro
print("Crie uma matriz 2D com 1 na borda e 0 dentro")
vetorNulo = np.ones((3,3))
vetorNulo[1:-1,1:-1] = 0
print(vetorNulo)

#Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
print("Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal")
vetorNulo = np.random.randint(4, size=(5,5))
#lower_sum = np.tril(A).sum()-np.trace(A)
print(np.tril(vetorNulo, -1))

#Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
print("Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)")
#vetorNulo = np.ndarray()
#print(vetorNulo)

#Subtrair a média de cada linha de uma matriz
print("Subtrair a média de cada linha de uma matriz")
vetorNulo = np.random.random((4,4))
print(vetorNulo.mean(axis=1)) #coluna
print(vetorNulo.mean(axis=0)) #linha

#Como encontrar o valor mais frequente em uma matriz?
print("Como encontrar o valor mais frequente em uma matriz?")
vetorNulo = np.random.randint(5, size=(10,10))
print(np.array(np.unique(vetorNulo, return_counts=True)).T)

#Crie uma matriz a partir de um arquivo
print("Crie uma matriz a partir de um arquivo")
#SaveFile
varSizeMatrix = "3,3"
f = open("sizeOfMatriz.txt", "w")
f.write(varSizeMatrix)
f.close()
#Load file

f = open("sizeOfMatriz.txt", "r")
readableSize = f.read()
f.close()
print(readableSize)
lin = int(readableSize.split(",")[0])
col = int(readableSize.split(",")[1])
vetorNulo = np.random.random((lin,col))
print(vetorNulo)

#Crie uma matriz com valores aletaórios e salve para um arquivo
print("Crie uma matriz com valores aletaórios e salve para um arquivo")
vetorNulo = np.random.random((8,8))
print(vetorNulo)
np.savetxt("randomMatrix.txt", vetorNulo)
readable = np.loadtxt("randomMatrix.txt")
print(readable)

Crie um vetor nulo de tamanho 10
[0.00e+000 4.94e-324 9.88e-324 1.48e-323 1.98e-323 8.40e-323 5.93e-323
 1.24e-322 1.19e-322 1.09e-322]
Como encontrar o tamanho da memória de qualquer matriz
80 bytes
Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
[0.00e+000 4.94e-324 9.88e-324 1.48e-323 1.98e-323 1.00e+000 5.93e-323
 1.24e-322 1.19e-322 1.09e-322]
Crie um vetor com valores que variam de 10 a 49
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
Inverter um vetor (o primeiro elemento se torna o último)
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
Crie uma matriz 3x3 com valores que variam de 0 a 8
[[4 1 4]
 [0 6 4]
 [0 5 3]]
Crie uma matriz de identidade 3x3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Crie uma matriz 3x3x3 com valores aleatórios
[[[0.64983051 0.62855788 0.66946645]
  [0.72271649 0.58701494 0.8264243 ]
  [0.64820774 0.179