# Exercícios:
 - Crie um array com 10 elementos usando a função arange

 - Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape

 - Crie duas matrizes bidimensionais com valores aleatórios calcule a transposta de cada matriz multiplique as duas matrizes

 - Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?

 - Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha

In [28]:
import numpy as np

arrayDezElementos = np.arange(5)
print("10 Elementos - ", arrayDezElementos)
print (" - - - - - ")
matrizReshape = np.zeros([1,10])
print("Transormando Original")
print(matrizReshape)
print("Transormando Reshape")
print(matrizReshape.reshape(2,5))
print (" - - - - - ")
matrizBiOne = np.random.random([2,2])
print("Matriz 1")
print(matrizBiOne)
print("Matriz 2")
matrizBiTwo = np.random.random([2,2])
print(matrizBiTwo)
print (" - - - - - ")
print("Matriz 1 - Transposta")
print(matrizBiOne.transpose())
print("Matriz 2 - Transposta")
print(matrizBiTwo.transpose())
print (" - - - - - ")
print("Matriz 1 X Matriz 2")
print(np.dot(matrizBiOne, matrizBiTwo))
print (" - - - - - ")
print ("Salvando")
np.savetxt("matrizBiOne.txt", matrizBiOne)
np.savetxt("matrizBiTwo.txt", matrizBiOne)
np.savetxt("multiplication.txt", np.dot(matrizBiOne, matrizBiTwo))
print (" - - - - - ")
print ("2 Matriz Bidimensional e Combina-las")
matrizBiOne = np.random.random([3,3])
print("Matriz 1")
print(matrizBiOne)
print("Matriz 2")
matrizBiTwo = np.random.random([3,3])
print(matrizBiTwo)
combiningMatriz = np.concatenate((matrizBiOne, matrizBiTwo), axis = 1)
print("Matriz combinada por linha (axis = 1) | coluna (axis = 0)")
print(combiningMatriz)

10 Elementos -  [0 1 2 3 4]
 - - - - - 
Transormando Original
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Transormando Reshape
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
 - - - - - 
Matriz 1
[[0.37389698 0.54513855]
 [0.62738767 0.97783364]]
Matriz 2
[[0.00909071 0.30004583]
 [0.82507378 0.63398073]]
 - - - - - 
Matriz 1 - Transposta
[[0.37389698 0.62738767]
 [0.54513855 0.97783364]]
Matriz 2 - Transposta
[[0.00909071 0.82507378]
 [0.30004583 0.63398073]]
 - - - - - 
Matriz 1 X Matriz 2
[[0.45317852 0.45779357]
 [0.8124883  0.80817274]]
 - - - - - 
Salvando
 - - - - - 
2 Matriz Bidimensional e Combina-las
Matriz 1
[[0.69129086 0.49537906 0.9886032 ]
 [0.4022992  0.38666568 0.12849174]
 [0.01423367 0.94309067 0.08238889]]
Matriz 2
[[0.43009427 0.05328514 0.34343248]
 [0.64189352 0.21412062 0.05104798]
 [0.20436447 0.1151536  0.02003963]]
Matriz combinada por linha (axis = 1) | coluna (axis = 0)
[[0.69129086 0.49537906 0.9886032  0.43009427 0.05328514 0.34343248]
 [0.4022992  0.38666568 0.12849174 0.641